name: Deploy to Github Pages

# Déclenche l'action manuellement aprés un push sur la branche "main"
on: 
  workflow_dispatch:
    branches:
      - main

# Définition des permissions et autorisation du déploiement sur github pages
permissions:
  contents: read
  pages: write

# Autorise un déploiement à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

# Définition des étapes d'intégration et de déploiement
jobs: 
  # INTEGRATION
  build:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      # Récupération du code du projet
      - name: Fetch code
        uses: actions/checkout@v4

      # Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Build du projet (transpilation ts -> js, scss -> css)
      - name: Build
        run: npm run build

      # Upload artefact vers github pages
      - name: Upload artefact to github pages
        uses: actions/upload-pages-artifact@v2
        with:
          name: artifact
          path: ./dist
  
  # DEPLOIEMENT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Configuration de github pages
      - name: Configure Github Pages
        uses: actions/configure-pages@v3
      # Deploiement sur github pages
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: artifact